modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/AntoCraft6/Quantum-Mod/issues/"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" //TODO
displayURL="https://github.com/AntoCraft6/Quantum-Mod/"
logoFile="quantum_machinery.png"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.quantummod]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.quantummod]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"